// Code generated by "qdiimpl"; DO NOT EDIT.
package main

import (
	"fmt"
	idata "github.com/rrgmc/qdiimpl/sample/datatype/idata"
	"runtime"
	"sync"
)

type QDSampleDataContext struct {
	ExecCount  int
	CallerFunc string
	CallerFile string
	CallerLine int
	Data       *idata.IData
}

type QDSampleData struct {
	Data *idata.IData

	lock      sync.Mutex
	execCount map[string]int
	fallback  SampleData
	implGet   func(qdCtx *QDSampleDataContext, name string) (any, error)
}

var _ SampleData = (*QDSampleData)(nil)

type QDSampleDataOption func(*QDSampleData)

func NewQDSampleData(options ...QDSampleDataOption) *QDSampleData {
	ret := &QDSampleData{execCount: map[string]int{}}
	for _, opt := range options {
		opt(ret)
	}
	return ret
}

// Get implements [main.SampleData.Get].
func (d *QDSampleData) Get(name string) (any, error) {
	if d.implGet == nil && d.fallback != nil {
		return d.fallback.Get(name)
	}
	return d.implGet(d.createContext("Get", d.implGet == nil), name)
}

func (d *QDSampleData) getCallerFuncName(skip int) (funcName string, file string, line int) {
	counter, file, line, success := runtime.Caller(skip)
	if !success {
		panic("runtime.Caller failed")
	}
	return runtime.FuncForPC(counter).Name(), file, line
}

func (d *QDSampleData) checkCallMethod(methodName string, implIsNil bool) (count int) {
	if implIsNil {
		panic(fmt.Errorf("[QDSampleData] method '%s' not implemented", methodName))
	}
	d.lock.Lock()
	defer d.lock.Unlock()
	d.execCount[methodName]++
	return d.execCount[methodName]
}

func (d *QDSampleData) createContext(methodName string, implIsNil bool) *QDSampleDataContext {
	callerFunc, callerFile, callerLine := d.getCallerFuncName(3)
	return &QDSampleDataContext{ExecCount: d.checkCallMethod(methodName, implIsNil), CallerFunc: callerFunc, CallerFile: callerFile, CallerLine: callerLine, Data: d.Data}
}

// Options

func WithData(data *idata.IData) QDSampleDataOption {
	return func(d *QDSampleData) {
		d.Data = data
	}
}
func WithFallback(fallback SampleData) QDSampleDataOption {
	return func(d *QDSampleData) {
		d.fallback = fallback
	}
}

// WithGet implements [main.SampleData.Get].
func WithGet(implGet func(qdCtx *QDSampleDataContext, name string) (any, error)) QDSampleDataOption {
	return func(d *QDSampleData) {
		d.implGet = implGet
	}
}
