// Code generated by "qdiimpl"; DO NOT EDIT.
package main

import (
	"fmt"
	"io"
	"runtime"
)

type DebugReaderContext struct {
	ExecCount  int
	CallerFunc string
	CallerFile string
	CallerLine int
}

type DebugReader struct {
	execCount map[string]int
	implRead  func(debugCtx *DebugReaderContext, p []byte) (n int, err error)
}

var _ io.Reader = (*DebugReader)(nil)

type DebugReaderOption func(*DebugReader)

func NewDebugReader(options ...DebugReaderOption) *DebugReader {
	ret := &DebugReader{execCount: map[string]int{}}
	for _, opt := range options {
		opt(ret)
	}
	return ret
}

func (d *DebugReader) Read(p []byte) (n int, err error) {
	return d.implRead(d.createContext("Read", d.implRead == nil), p)
}

func (d *DebugReader) getCallerFuncName(skip int) (funcName string, file string, line int) {
	counter, file, line, success := runtime.Caller(skip)
	if !success {
		panic("runtime.Caller failed")
	}
	return runtime.FuncForPC(counter).Name(), file, line
}

func (d *DebugReader) checkCallMethod(methodName string, implIsNil bool) (count int) {
	if implIsNil {
		panic(fmt.Errorf("[DebugReader] method '%s' not implemented", methodName))
	}
	d.execCount[methodName]++
	return d.execCount[methodName]
}

func (d *DebugReader) createContext(methodName string, implIsNil bool) *DebugReaderContext {
	callerFunc, callerFile, callerLine := d.getCallerFuncName(3)
	return &DebugReaderContext{ExecCount: d.checkCallMethod(methodName, implIsNil), CallerFunc: callerFunc, CallerFile: callerFile, CallerLine: callerLine}
}

// Options

func WithDebugReaderRead(implRead func(debugCtx *DebugReaderContext, p []byte) (n int, err error)) DebugReaderOption {
	return func(d *DebugReader) {
		d.implRead = implRead
	}
}
